### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by Adriel-Cabral** [jhwjhw0123/Imbalance-XGBoost#10]
When a try run the code:

xgboster_focal.fit(X_test, y_test)

I have this Warning

[00:02:37] WARNING: ../src/learner.cc:516: 
Parameters: { silent } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.

Can you helpme ?

**Comment by jhwjhw0123** [comment]
Thanks for letting us know. We'll take a look at this issue. From memory, I think it's probably the issue of version compatibility -- there was a version that you had to specify `silent.'

For the purpose of an application, you can ignore the warning for now, and if you don't want to disable all warnings, I believe Python offers warning control on specific lines/messages.

**Comment by jhwjhw0123** [comment]
The issue has been resolved in version 0.8.1. Indeed the warning was because the argument `silent' was deprecated in the newer xgboost releases.
