### ISSUE TITLE
Saving trained models

### ISSUE THREAD

**Issue by vbonvin** [jhwjhw0123/Imbalance-XGBoost#3]
Hi,

I'm trying to save models after training:

```javascript
from imxgboost.imbalance_xgb import imbalance_xgboost as imb_xgb
xgbooster_focal = imb_xgb(special_objective='focal', focal_gamma=1.0)
xgbooster_focal.fit(X_train.values, y_train["label"].values)
joblib.dump(xgbooster_focal, '../models/xgboost_focal.pkl') 
```

but it doesn't work, apparently a pointer issue:

```javascript
ValueError                                Traceback (most recent call last)
<ipython-input-30-d4caae048667> in <module>
      1 # save model (or try to)
----> 2 joblib.dump(xgbooster_focal, '../models/xgboost_focal.pkl')

...

ValueError: ctypes objects containing pointers cannot be pickled
```
See the full error log [on this gist](https://gist.github.com/vbonvin/3823b33eb61de7ed658298ebf0fa8371).

FYI, the same save method works well on regular xgboost models running on the same data. 

Any idea how to solve that?

**Comment by jhwjhw0123** [comment]
I think you can do `trained_booster = xgbooster_focal .booster` to retrieve the vanilla xgboost booster and save it with the same method on regular xgboost models.
