### ISSUE TITLE
use evaluation dataset

### ISSUE THREAD

**Issue by ramdhan1989** [jhwjhw0123/Imbalance-XGBoost#9]
in original xgboost fit method we could use early stopping by using eval_metric and eval_set. is there anyway to use this using this repo ?

thank you

**Comment by jhwjhw0123** [comment]
Thanks for the suggestion. We'll take a look into this.

**Comment by jhwjhw0123** [comment]
As for version 0.8.1, now you can specify the argument `early_stopping_rounds' when initializing/instantiating the object.
